<?php
$flash=$this->flashMessenger()
            ->setMessageOpenFormat('<div%s>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</div>');

$form=$this->form;
$form->prepare();
//Definimos el atributo action y method
$form->setAttributes(array(
	'action'=>$this->url.'/lector/lectura/insercion',
	'method'=>'POST'
));

//Uilizamos el plugin para mostrar los label

$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);
?>

<div class='form_element'>
<?php
	//imprime el campo nombre
	$nombre=$form->get('txtNombre');
	echo $formLabel->openTag().$nombre->getOption('label')." ";
	echo $this->formInput($nombre);
	echo $formLabel->closeTag();
?>
</div>
<div class="form_element">
<?php
	//imprime el campo email con modificaciones
	$email=$form->get('txtEmail');
	echo $formLabel->openTag().$email->getOption('label')." ";
	echo $this->formInput($email);
	echo $formLabel->closeTag();
?>
</div>

<?php
echo $this->formElement($form->get('submit'));
?>
<a id="listar" class="btn btn-success" href="<?=$this->basePath()?>/lector/lectura/listar">Listar</a>
<div id='usuarios'></div>
<?php
echo $flash->render('add_correcto',array('btn', 'btn-success'));
?>

<script>
	$(document).ready(function(){
		$('#listar').click(function(){
			$.ajax({
				async: true,
				type: 'POST',
				url: '<?=$this->url."/lector/lectura/listar"?>',
				success: function(data){
					$('#usuarios').html(data);
				}
			});
			return false;
		});
	}
	);
</script>