<?php
//print_r($this->lista);
?>
<table class="table">
<?php
foreach ($this->lista as $usuario) {
	if($usuario['estado']==1){
	?>
    <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
        <td><?=$usuario["id"]?></td>
        <td><?=$usuario["email"]?></td>
        <td><?=$usuario["nombre"]." ".$usuario["apellido"]?></td>
        <td><a class="btn btn-primary" href="<?=$this->basePath()?>/lector/lectura/ver/<?=$usuario["id"]?>">Modificar</a></td>
        <td><a class="btn btn-danger" href="<?=$this->basePath()?>/lector/lectura/eliminar/<?=$usuario["id"]?>">Eliminar</a></td>
    </tr>
    <?php
}
}
?>
</table>

<a class="btn btn-success" href="<?=$this->basePath()?>/lector/lectura/index">Nuevo</a>