<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'Lector',
        'Application',
        'Modulo',
        'Visitar',
        'Moel',
        'Usuario',
        'Cron',
        'Prueba',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
            './websites',
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php',
        ),
    ),
);
