<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PruebaWebSite\Module'                        => __DIR__ . '/Module.php',
    'PruebaWebSite\Controller\PruebaWebSiteController' => __DIR__ . '/src/PruebaWebSite/Controller/PruebaWebSiteController.php',
    'ZendSkeletonModuleTest\Framework\TestCase'        => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
    'ZendSkeletonModuleTest\SampleTest'                => __DIR__ . '/tests/ZendSkeletonModule/SampleTest.php',
);