<?php
//Comprobamos si nos llega la sesión correcta o no, esto se puede hacer de distintas formas
if(!is_string($this->datos)){
//var_dump($this->datos->id);
echo "Bienvenido ".$this->datos->nombre." ".$this->datos->apellido."<br/>";
echo "Estas identificado con ".$this->datos->email;

echo "<br>Este es tu id de session";?><span class="label label-success"><?=$sesion->id;
?>
</span>
<p>
    <a class="btn btn-success" href="<?=$this->basePath("usuario/usuario/cerrar")?>">Cerrar sesión</a>
</p>  
<?php 
}else{
    echo $this->datos;
}
/*
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="form_element">
<?php
    $email = $form->get('email');
    echo "Correo: ".$this->formInput($email);
    if(isset($error["email"])){
      echo $error["email"]['emailAddressInvalidHostname'];
    }
?>
</div>

<?php
echo $this->flashMessenger()->render();
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
?>*/