<?php
    if (defined('RUNNING_FROM_ROOT')) {
        $this->plugin('basePath')->setBasePath($this->basePath().'/public');
} ?>
	<h1>Login en Zend Framework 2</h1>
<hr/>
<?php
$this->headTitle("Login usuarios");
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="form_element">
<?php
    $email = $form->get('email');
    echo "Correo: ".$this->formInput($email);
    if(isset($error["email"])){
      echo $error["email"]['emailAddressInvalidHostname'];
    }
?>
</div>
<div class="form_element">
<?php
    $pass = $form->get('pasword');
    echo "Contraseña: ".$this->formInput($pass);
    echo $this->formElementErrors($pass);
?>
</div>
<?php
echo $this->flashMessenger()->render();
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
?>