<h1><?php echo $this->titulo?></h1>
<?php
//preparamos el formulario
$form=$this->form;
$form->prepare();
//Definimos el atributo action y method
$form->setAttributes(array(
	'action'=>$this->url.'/modulo/prueba/recibirormulario',
	'method'=>'post'
));

//Uilizamos el plugin para mostrar los label
$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);
?>

<div class='form_element'>
<?php
	//imprime el campo nombre
	$nombre=$form->get('nombre');
	echo $formLabel->openTag().$nombre->getOption('label')." ";
	echo $this->formInput($nombre);
	echo $formLabel->closeTag();
/*?>
</div>

<div class='form_element'>
<?php
	//imprime el campo email
	$email = $form->get('email');
	echo $formLabel->openTag().$email->getOption('label')." ";
	echo $this->formInput($email);
	echo $formLabel->closeTag();*/
?>
</div>
<?php
//imprime el boton submit
echo $this->formElement($form->get('submit'));

//cerramos el formulario
echo $this->form()->closeTag();

?>
